#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#7524de

# Autostart
$HOME/.config/polybar/launch.sh

# Rules
bspc rule -a steam desktop='^2' follow=on
bspc rule -a Waypaper state=floating
